MultitenantProductCustomization/MultitenantProductCustomization/Models/Shared/CheckBoxListItem.cs
namespace MultiTenantProductCustomization.Models.Shared
{
	public class CheckBoxListItem
	{
		public int Id { get; set; }

		public string DisplayName { get; set; }

		public bool Value { get; set; }
	}
}

MultitenantProductCustomization/MultitenantProductCustomization/Models/Shared/CheckedGroupListItem.cs
using System.Collections.Generic;

namespace MultiTenantProductCustomization.Models.Shared
{
	public class CheckedGroupListItem
	{
		public int Id { get; set; }

		public string DisplayName { get; set; }

		public List<CheckBoxListItem> Options { get; set; }

	}
}

MultitenantProductCustomization/MultitenantProductCustomization/Models/Shared/ItemWitnName.cs

namespace MultiTenantProductCustomization.Models.Shared
{
	public class ItemWitnName
	{
		public int Id { get; set; }

		public string DisplayName { get; set; }
	}
}

MultitenantProductCustomization/MultitenantProductCustomization/Models/Shared/RadioGroupListItem.cs
using System.Collections.Generic;

namespace MultiTenantProductCustomization.Models.Shared
{
	public class RadioGroupListItem
	{
		public string DisplayName { get; set; }

		public List<ItemWitnName> Options { get; set; }
		
		public int? Value { get; set; } 
	}
}

MultitenantProductCustomization/MultitenantProductCustomization/Controllers/ProductManagement/ProductAttributesController.cs
using System.Linq;
using System.Web.Mvc;
using MultiTenantProductCustomization.DomainModel.Products;
using MultiTenantProductCustomization.Models.Products;
using MultiTenantProductCustomization.Models.Shared;

namespace MultiTenantProductCustomization.Controllers.ProductManagement
{
	public class ProductAttributesController : ProductControllerBase
	{
		public ActionResult Index()
		{
			var model = Context.ProductAttributes.Select(x => new ItemWitnName {Id = x.Id, DisplayName = x.Name}).ToList();
			return View(model);
		}

		public ActionResult View(int id)
		{
			var category = Context.GetAtrAttribute(id);
			var model = new ProductAttributeModel(category);
			return View(model);
		}

		[HttpPost]
		public ActionResult Create(AttributeModel model)
		{
			var productAttribute = new ProductAttribute {Name = model.Name};
			Context.ProductAttributes.Add(productAttribute);
			Context.SaveChanges();
			return RedirectToAction("View", new {id = productAttribute.Id});
		}

		public ActionResult Create()
		{
			return View(new AttributeModel());
		}
	}
}

MultitenantProductCustomization/MultitenantProductCustomization/Controllers/ProductManagement/ProductCategoriesController.cs
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using MultiTenantProductCustomization.DomainModel.Products;
using MultiTenantProductCustomization.Models.Products;
using MultiTenantProductCustomization.Models.Shared;

namespace MultiTenantProductCustomization.Controllers.ProductManagement
{
    public class ProductCategoriesController : ProductControllerBase
	{
		public ActionResult Index()
		{
			var productCategories = Context
				.ProductCategories
				.Select(x => new ItemWitnName {DisplayName = x.Name, Id = x.Id}).ToList();
			return View(productCategories);
		}

		[HttpPost]
		public ActionResult Edit(ProductCategoryModel model)
		{
			UpdateProductCategory(model);
			return RedirectToAction("Index");
		}

	    private void UpdateProductCategory(ProductCategoryModel model)
	    {
		    ProductCategory result;
		    if (model.Id>0)
		    {
			    result = Context.ProductCategories.Find(model.Id);
			}
			else
		    {
				result = new ProductCategory();
		    }

			Context.Entry(result).State = result.Id==0?EntityState.Added : EntityState.Modified;
		    result.Name = model.Name;
			var attributeCategoryIds = model.ProductCategories.Where(x=>x.Value).Select(x => x.Id).ToList();
			var categories = Context.ProductAttributes.Where(x => attributeCategoryIds.Contains(x.Id)).ToList();
			result.Attributes.Clear();
			categories.ForEach(result.Attributes.Add);
			Context.SaveChanges();
		}

	    public ActionResult Edit(int? id)
	    {
		    var productCategory = id == null ? new ProductCategory() : Context.ProductCategories.Find(id);
			if(productCategory==null)
				return HttpNotFound();

			var model = new ProductCategoryModel(Context, productCategory);
			return View( model);
	    }
    }
}

MultitenantProductCustomization/MultitenantProductCustomization/Views/Shared/_Layout.cshtml
@using MultiTenantProductCustomization.Infastructure.TenantsManagement
@using MultiTenantProductCustomization.IoC
@using Microsoft.Practices.Unity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Custom fields</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <font color ="white">
                            Current tenant - @Html.Label(IoCManager.Container.Resolve<ITenantManager>().GetCurrentTenantName() ?? "NOT SELECTED YET")
                        </font>
                    </li>
                    <li>@Html.ActionLink("Tenants", "Index", "Tenants")</li>
                    <li>@Html.ActionLink("Product Categories", "Index", "ProductCategories")</li>
                    <li>@Html.ActionLink("Product Attributes", "Index", "ProductAttributes")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>